### PR TITLE
I made some small changes in your project

### PR DESCRIPTION
**Pull request by valdergallo**
# Depricated
- *command* seal() hash is im memory
- *command* validate() can be removed now

# New features

- *hash*  is auto calculate
- *prev_hash* is auto calculate
- *bugfix* str(None) was returning 'None' in hash
- *bugfix* stop to check all the time the class context and validate

```python
In [1]: from easychain.blockchain import *
In [2]: %cpaste
Pasting code; enter '--' alone on the line to stop or use Ctrl-D.
:def get_messages(*args):
:    content = []
:    last_msg = None
:    for arg in args:
:        msg = Message(arg)
:        content.append(msg)
:        if last_msg:
:            msg.link(last_msg)
:        last_msg = msg
:    return content
:<EOF>
In [3]: msgs = get_messages("first", "second", "third", "fourth", "fifth")

In [4]: [i.hash for i in msgs]
Out[4]:
['576c7599ac25730b29fe334537f4e63c6cd6df168c5f130ebb574ff01fa44c80',
 '2ceff64c8304e51efb14a23ed3f56fc2331ed98b04db3c0901dc1c487fe6a402',
 '60f4c82e01a1523edc0f0dda4e55c385483f61fcc51f9c23f31caeedfe6533f4',
 '65f520f38d67b17edca6e2e02b7e5c2bc12048a018d23ebc88bd6fd3ab7fc23c',
 '05c98be26168e6b23d24b990a2cabbe053e05106ff147f52a713f3f89f47fde3']

In [5]: msgs[1].data = 'changed'

In [6]: [i.hash for i in msgs]
Out[6]:
['576c7599ac25730b29fe334537f4e63c6cd6df168c5f130ebb574ff01fa44c80',
 '4571d216f229ff85816ba0a09b7a26e01c66ab6d0468e5ef224e8a001e36bb2e',
 'fa4c9bea8f0025295f248c6ad3bd4caf31c9a8aebae0cf19a8c508642a2e5500',
 '531a69e94f4b43d4a874d90b7e6aadcb22004d1d10080e10a935c3d628c67fb4',
 '84d94084e4278fb178a46b659f4db99720df9b32ace217b6fd05c69dd062abf8']
```

### CODE REVIEW

**Comment by valdergallo** [comment]
I'll create one setup.py to send this app to pypi ... Can you help me with the documentation ?

**Comment by valdergallo** [comment]
done!
```
(.env) valdergallo@deathstar ~/www/easychain-pack/easychain (master) $ pytest . -s -v
==================================================================== test session starts =====================================================================
platform darwin -- Python 3.6.3, pytest-3.4.2, py-1.5.2, pluggy-0.6.0
benchmark: 3.1.1 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /Users/valdergallo/www/easychain-pack/easychain, inifile: pytest.ini
plugins: freezegun-0.2.0, benchmark-3.1.1
collected 24 items

tests/test_benchmark.py ...
tests/test_block.py ........
tests/test_blockchain.py .....
tests/test_message.py ........


---------------------------------------------------------------------------------------- benchmark: 3 tests ----------------------------------------------------------------------------------------
Name (time in us)          Min                   Max                Mean              StdDev              Median                 IQR            Outliers  OPS (Kops/s)            Rounds  Iterations
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_message_hash      16.0240 (1.0)        738.3980 (1.0)       21.6344 (1.0)       12.4920 (1.0)       16.7940 (1.0)        6.7310 (1.0)       667;707       46.2227 (1.0)        9236           1
test_block            169.7150 (10.59)    3,002.6900 (4.07)     216.3915 (10.00)     92.3063 (7.39)     180.7750 (10.76)     51.1340 (7.60)      301;302        4.6213 (0.10)       2331           1
test_blockchain       281.4970 (17.57)    5,097.0920 (6.90)     361.2349 (16.70)    146.6515 (11.74)    296.5370 (17.66)    107.5808 (15.98)     453;235        2.7683 (0.06)       3223           1
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Legend:
  Outliers: 1 Standard Deviation from Mean; 1.5 IQR (InterQuartile Range) from 1st Quartile and 3rd Quartile.
  OPS: Operations Per Second, computed as 1 / Mean
================================================================= 24 passed in 3.68 seconds ==================================================================
```

**Comment by valdergallo** [comment]
support for py2
```
(.env2)valdergallo@deathstar ~/www/easychain-pack/easychain (master) $ python setup.py test
running test
running egg_info
writing easychain.egg-info/PKG-INFO
writing top-level names to easychain.egg-info/top_level.txt
writing dependency_links to easychain.egg-info/dependency_links.txt
reading manifest file 'easychain.egg-info/SOURCES.txt'
writing manifest file 'easychain.egg-info/SOURCES.txt'
running build_ext
==================================================================== test session starts =====================================================================
platform darwin -- Python 2.7.10, pytest-3.4.2, py-1.5.2, pluggy-0.6.0
benchmark: 3.1.1 (defaults: timer=time.time disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /Users/valdergallo/www/easychain-pack/easychain, inifile: pytest.ini
plugins: benchmark-3.1.1, freezegun-0.2.0
collected 24 items

tests/test_benchmark.py ...                                                                                                                            [ 12%]
tests/test_block.py ........                                                                                                                           [ 45%]
tests/test_blockchain.py .....                                                                                                                         [ 66%]
tests/test_message.py ........                                                                                                                         [100%]


---------------------------------------------------------------------------------------- benchmark: 3 tests ---------------------------------------------------------------------------------------
Name (time in us)          Min                   Max                Mean              StdDev              Median                IQR            Outliers  OPS (Kops/s)            Rounds  Iterations
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_message_hash       7.8678 (1.0)        137.0907 (1.0)       11.3248 (1.0)        5.6259 (1.0)        9.0599 (1.0)       5.0068 (1.0)       768;617       88.3018 (1.0)        7571           1
test_block            142.8127 (18.15)      598.9075 (4.37)     173.2525 (15.30)     61.8621 (11.00)    145.9122 (16.11)    13.1130 (2.62)      272;535        5.7719 (0.07)       2349           1
test_blockchain       264.8830 (33.67)    1,078.8441 (7.87)     322.4525 (28.47)    105.6944 (18.79)    270.1283 (29.82)    67.1148 (13.40)     388;381        3.1012 (0.04)       3436           1
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Legend:
  Outliers: 1 Standard Deviation from Mean; 1.5 IQR (InterQuartile Range) from 1st Quartile and 3rd Quartile.
  OPS: Operations Per Second, computed as 1 / Mean
================================================================= 24 passed in 3.94 seconds ==================================================================
```

**Comment by davecan** [comment]
Hello! Sorry for the late response, I've been extremely busy and not monitoring email.

These are some interesting changes. Can you elaborate a bit on the goal? e.g. why you want to deprecate seal() and validate() etc.

Also github reports the original repository that you used to submit this has been deleted, so it closed the pull request. Let me know if you are still interested in merging and I'll be happy to discuss, just keep in mind it may be a few days before I can respond.

Thanks!
Dave

**Comment by valdergallo** [comment]
Hi Dave, 

I made one new project with same name, because the pypi project. 
I can recreate the fork, this is not a problem. But I would like to have access to create tags for new versions in this project.

#### Why remove *seal()* and *validation()*. 
     + Python has @property ... "one class attribute that works as function without args".
     + You are saving the content in strings, but is more better use the objects in memory. 

Some thing like:

```python

>>>class A(object):
>>>    value = None
>>>a = A()
>>>b = a
>>>a.value = 1
>>>b.value
1
```

My chages was based in this pattern. The hashs will been shared in other objects, not recreated. 
And the @propert works like one obsever, that will recreate the hash, if need.

Thanks!

**Pull request closed without merging**
